### ISSUE TITLE
During bootstrap portion, fails.

### ISSUE THREAD

**Issue by brimdor** [khuedoan/homelab#102] opened 2023-01-17 04:02 UTC
After initializing the build with 'make', there are no issues till bootstrap starts. It fails and provides an error. I am not sure how to decypher it. When I run 'make' again, no issues.

```
----ERROR MESSAGE START----
make[1]: Leaving directory '/home/brimdor/homelab/metal'
make -C bootstrap
make[1]: Entering directory '/home/brimdor/homelab/bootstrap'
kubectl create namespace argocd --dry-run=client --output=yaml \
    | kubectl apply -f -
namespace/argocd created
cd argocd && ./apply.sh
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "applications.argoproj.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "applicationsets.argoproj.io" not found
make[1]: *** [Makefile:11: argocd] Error 1
make[1]: Leaving directory '/home/brimdor/homelab/bootstrap'
make: *** [Makefile:18: bootstrap] Error 2
----ERROR MESSAGE END----
```

### To reproduce
I can reproduce this by just running the process normally.

1. Run `make tools`
2. Run `make configure`
3. Fill out the items requested
4. Run 'make'
5. When bootstrap starts the initial script, it fails according to the info pasted above.

### Expected behavior

Running 'make' should allow the process to run complete without being interrupted by this bootstrap portion.

### Additional context

Using the same hardware and software as khuedoan.

**Comment by khuedoan** [comment] 2023-01-20 10:37
Hmmm I can't reproduce this in my environment, can you please try again with this flag in the apply scripts to gather more info:

- [bootstrap/argocd/apply.sh](https://github.com/khuedoan/homelab/blob/349faa386eb7f5ee667f12c676d5b00a91677192/bootstrap/argocd/apply.sh#L2)
- [bootstrap/root/apply.sh](https://github.com/khuedoan/homelab/blob/349faa386eb7f5ee667f12c676d5b00a91677192/bootstrap/root/apply.sh#L2)

```diff 
  #!/bin/sh

+ set -ex
```

**Comment by brimdor** [comment] 2023-01-20 22:54
Here is the latest error message after applying set -ex to the files you stated.

`make[1]: Leaving directory '/home/brimdor/homelab/metal'
make -C bootstrap
make[1]: Entering directory '/home/brimdor/homelab/bootstrap'
kubectl create namespace argocd --dry-run=client --output=yaml \
        | kubectl apply -f -
namespace/argocd created
cd argocd && ./apply.sh
+ helm template --dependency-update --include-crds --namespace argocd argocd .
+ kubectl apply -n argocd -f -
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
make[1]: *** [Makefile:11: argocd] Error 1
make[1]: Leaving directory '/home/brimdor/homelab/bootstrap'
make: *** [Makefile:18: bootstrap] Error 2`

**Comment by brimdor** [comment] 2023-01-20 23:24
```
make[1]: Leaving directory '/home/brimdor/homelab/metal'
make -C bootstrap
make[1]: Entering directory '/home/brimdor/homelab/bootstrap'
kubectl create namespace argocd --dry-run=client --output=yaml \
        | kubectl apply -f -
namespace/argocd created
cd argocd && ./apply.sh
+ helm template --dependency-update --include-crds --namespace argocd argocd .
+ kubectl apply -n argocd -f -
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
make[1]: *** [Makefile:11: argocd] Error 1
make[1]: Leaving directory '/home/brimdor/homelab/bootstrap'
make: *** [Makefile:18: bootstrap] Error 2
```

**Comment by brimdor** [comment] 2023-01-20 23:29
Now this is happening
```
ingress.networking.k8s.io/argocd-server created
resource mapping not found for name: "argocd-application-controller" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "argocd-repo-server" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "argocd-server" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "argocd-redis" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
make[1]: *** [Makefile:11: argocd] Error 1
make[1]: Leaving directory '/home/brimdor/homelab/bootstrap'
make: *** [Makefile:18: bootstrap] Error 2
```

**Comment by brimdor** [comment] 2023-01-20 23:37
I removed `set -ex` from both apply.sh files and I am able to get past the latest error.

**Comment by brimdor** [comment] 2023-01-21 17:59
I am regretting rebuilding to help troubleshoot this issue. Now Cloudflare is not populating the DNS records. It's only setting up the tunnel. When it runs the bootstrap/argocd/apply.sh, I get errors regarding the CRDs.

```ingress.networking.k8s.io/argocd-server unchanged
resource mapping not found for name: "argocd-application-controller" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "argocd-repo-server" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "argocd-server" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
resource mapping not found for name: "argocd-redis" namespace: "" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first```

**Comment by khuedoan** [comment] 2023-01-22 04:59
Thanks for taking the time to rebuild, the `ServiceMonitor` warning is safe to ignore.
Do you have the logs for `external-dns` pod (which is responsible for updating DNS records)?

**Comment by brimdor** [comment] 2023-01-22 05:23
I don't. This is all new to me so I failed to collect certain items or even
know where to look when things go wrong. I eventually got the environment
back when I ran each piece manually.
make metal, then make bootstrap, then make external, etc

**Comment by khuedoan** [comment] 2023-01-22 05:26
I disabled `ServiceMonitor` on first apply to avoid the confusion caused by the warning https://github.com/khuedoan/homelab/commit/cd39632439e0d57a1a0fcbed5cc7d80845e2498f

**Comment by khuedoan** [comment] 2023-01-22 05:27
You can use the `k9s` command included in the tools container to list the pods (it has vim bindings).

**Comment by brimdor** [comment] 2023-05-21 02:19
FYI: I had to rebuild and I get this same issue even with the latest pull of your respository.
I have some hardware coming in couple days that will allow me to do more troubleshooting without taking down my entire server build every time. Unfortunately, the issue is persistent and it seems if I run 'make' again after that, it goes through no problem. Same as before.

**Comment by khuedoan** [comment] 2023-05-21 05:22
You can use a VM to test without additional hardware, here's what I usually do:

- Create an empty VirtualBox VM with UEFI boot and bridged network
- Update a `stag.yml` inventory
- Run `make`
- Boot to the boot menu and select network boot, it will boot just like a normal hardware

**Comment by brimdor** [comment] 2023-05-29 17:10
It seems to be a time issue. The time for the namespace to be created before it can move forward. I added 'sleep 10' then 'sleep 30' then 'sleep 60' to line 7 in bootstrap/Makefile, tabbed in line with the kubectl command and it worked when I did sleep 60. 30 and 10 were not long enough wait times.

**Comment by khuedoan** [comment] 2023-05-29 17:16
Hmmm that's strange, there's a wait command in the install script that _supposed_ to wait for `argocd` to complete before continuing with `bootstrap`:

https://github.com/khuedoan/homelab/blob/4b69ec2dfc1305155d4f0090361e0e7136b27445/bootstrap/argocd/apply.sh#L16-L18

Do you have any config related to parallel jobs (for example `make -j 4`)?

**Comment by brimdor** [comment] 2023-05-29 19:25
The only changes are from make configure and the sleep 60. Everything else is out of the box experience that you have in your repo.

**Comment by brimdor** [comment] 2023-05-30 19:56
excuse the sleep 60 option. I was able to fix it using a condition that allows it to fix it if the conditions aren't met. Here is the updated bootstrap/Makefile:
```.POSIX:

default: namespace argocd root

namespace:
        kubectl create namespace argocd --dry-run=client --output=yaml | kubectl apply -f -

.PHONY: argocd
argocd:
        kubectl get customresourcedefinitions.apiextensions.k8s.io applications.argoproj.io applicationsets.argoproj.io > /dev/null || kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml && cd argocd && ./apply.sh

.PHONY: root
root:
        cd root && ./apply.sh```

And here are the results showing a positive outcome:
```[nix-shell:/home/brimdor/homelab]# make bootstrap
make -C bootstrap
make[1]: Entering directory '/home/brimdor/homelab/bootstrap'
kubectl create namespace argocd --dry-run=client --output=yaml | kubectl apply -f -
namespace/argocd created
kubectl get customresourcedefinitions.apiextensions.k8s.io applications.argoproj.io applicationsets.argoproj.io > /dev/null || kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml && cd argocd && ./apply.sh
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "applications.argoproj.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "applicationsets.argoproj.io" not found
customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/applicationsets.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/appprojects.argoproj.io created
serviceaccount/argocd-application-controller created
serviceaccount/argocd-applicationset-controller created
serviceaccount/argocd-dex-server created
serviceaccount/argocd-notifications-controller created
serviceaccount/argocd-redis created
serviceaccount/argocd-repo-server created
serviceaccount/argocd-server created
role.rbac.authorization.k8s.io/argocd-application-controller created
role.rbac.authorization.k8s.io/argocd-applicationset-controller created
role.rbac.authorization.k8s.io/argocd-dex-server created
role.rbac.authorization.k8s.io/argocd-notifications-controller created
role.rbac.authorization.k8s.io/argocd-server created
clusterrole.rbac.authorization.k8s.io/argocd-application-controller created
clusterrole.rbac.authorization.k8s.io/argocd-server created
rolebinding.rbac.authorization.k8s.io/argocd-application-controller created
rolebinding.rbac.authorization.k8s.io/argocd-applicationset-controller created
rolebinding.rbac.authorization.k8s.io/argocd-dex-server created
rolebinding.rbac.authorization.k8s.io/argocd-notifications-controller created
rolebinding.rbac.authorization.k8s.io/argocd-redis created
rolebinding.rbac.authorization.k8s.io/argocd-server created
clusterrolebinding.rbac.authorization.k8s.io/argocd-application-controller created
clusterrolebinding.rbac.authorization.k8s.io/argocd-server created
configmap/argocd-cm created
configmap/argocd-cmd-params-cm created
configmap/argocd-gpg-keys-cm created
configmap/argocd-notifications-cm created
configmap/argocd-rbac-cm created
configmap/argocd-ssh-known-hosts-cm created
configmap/argocd-tls-certs-cm created
secret/argocd-notifications-secret created
secret/argocd-secret created
service/argocd-applicationset-controller created
service/argocd-dex-server created
service/argocd-metrics created
service/argocd-notifications-controller-metrics created
service/argocd-redis created
service/argocd-repo-server created
service/argocd-server created
service/argocd-server-metrics created
deployment.apps/argocd-applicationset-controller created
deployment.apps/argocd-dex-server created
deployment.apps/argocd-notifications-controller created
deployment.apps/argocd-redis created
deployment.apps/argocd-repo-server created
deployment.apps/argocd-server created
statefulset.apps/argocd-application-controller created
networkpolicy.networking.k8s.io/argocd-application-controller-network-policy created
networkpolicy.networking.k8s.io/argocd-applicationset-controller-network-policy created
networkpolicy.networking.k8s.io/argocd-dex-server-network-policy created
networkpolicy.networking.k8s.io/argocd-notifications-controller-network-policy created
networkpolicy.networking.k8s.io/argocd-redis-network-policy created
networkpolicy.networking.k8s.io/argocd-repo-server-network-policy created
networkpolicy.networking.k8s.io/argocd-server-network-policy created
Error from server (NotFound): ingresses.networking.k8s.io "argocd-server" not found
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io condition met
customresourcedefinition.apiextensions.k8s.io/applicationsets.argoproj.io condition met
cd root && ./apply.sh
Error from server (NotFound): namespaces "gitea" not found
applicationset.argoproj.io/bootstrap created
applicationset.argoproj.io/system created
applicationset.argoproj.io/platform created
applicationset.argoproj.io/apps created
make[1]: Leaving directory '/home/brimdor/homelab/bootstrap'```

**Comment by Moortu** [comment] 2024-01-28 21:59
I had the same issue, I used brimdor's solution.
I also changed the chart verison to 5.53.9 but I don't know if that had any effect

**Comment by brimdor** [comment] 2024-03-10 15:13
I discovered what seems to be a 100% success rate to fix this issue. The sleep and condition methods weren't working every time. I think it had something to do with caching but not certain.

If anyone wants to test this, here is out it works.

helm creates a basic version of argocd environment, then it's followed up with the same command as before, running apply.sh from bootstrap/argocd.

```
.POSIX:

default: namespace argocd root

namespace:
    kubectl create namespace argocd --dry-run=client --output=yaml \
        | kubectl apply -f -

# .PHONY: argocd
# argocd:
#     cd argocd && ./apply.sh

.PHONY: argocd
argocd:
    helm upgrade --install argocd argocd \
    --namespace argocd \
    --dependency-update
    cd argocd && ./apply.sh

.PHONY: root
root:
    cd root && ./apply.sh
```

**Comment by khuedoan** [comment] 2024-03-31 09:19
I'm working on a refactor of the bootstrap process that will utilize server-side apply, this should permanently fix this issue without the need for a workaround.

**Comment by khuedoan** [comment] 2024-04-19 02:52
Should be fixed by https://github.com/khuedoan/homelab/commit/8d00d55eb1faa214b29ab73fb0405351d47b079b with server side apply.

**Closed by khuedoan** 2024-04-19 02:52 UTC
Labels: bug
