### ISSUE TITLE
Unable to recognize "STDIN": no matches for kind "ServiceMonitor"...

### ISSUE THREAD

**Issue by emacsified** [khuedoan/homelab#29] opened 2022-01-25 20:21 UTC
Hey,

I've set up my VMs in proxmox, in the same way documented in #17.

I am, however, running into the following when running the `make` command:

```
service/argocd-redis unchanged
service/argocd-argocd-applicationset unchanged
deployment.apps/argocd-application-controller unchanged
deployment.apps/argocd-repo-server unchanged
deployment.apps/argocd-server unchanged
deployment.apps/argocd-dex-server unchanged
deployment.apps/argocd-redis unchanged
deployment.apps/argocd-argocd-applicationset unchanged
ingress.networking.k8s.io/argocd-server unchanged
unable to recognize "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io condition met
customresourcedefinition.apiextensions.k8s.io/applicationsets.argoproj.io condition met
```

This continues to run okay, but leaves me with only the following in the `get-status` script:

```
NAME        AGE
apps        104m
bootstrap   104m
platform    104m
system      104m
No resources found in argocd namespace.
NAMESPACE   NAME            CLASS   HOSTS                ADDRESS   PORTS     AGE
argocd      argocd-server   nginx   argocd.ashmcbri.de             80, 443   104m
```

The remainder don't get set up, assumedly because of these errors.

**Comment by khuedoan** [comment] 2022-01-26 01:54
This is expected because Prometheus is not installed yet, it will be synced automatically after Prometheus is installed, you can safely ignore.

The status will take a few minutes so you just need to wait a bit. You can visit the dashboard early using:

```
kubectl port-forward service/argocd-server 8000:80 -n argocd
```

**Comment by khuedoan** [comment] 2022-01-26 16:18
Closing this one since this is working as intended.

**Closed by khuedoan** 2022-01-26 16:18 UTC

**Comment by emacsified** [comment] 2022-01-26 18:23
For reference, this was because I'd set my git repo URL as `https://github...` but the link provided to `configure.py` is prefaced with `https` leading to the applicationsets saying:
Error during fetching repo: `git fetch origin master --tags --force` failed exit status 128: fatal: unable to access 'https://https://github.com.../': Could not resolve host: https

**Comment by khuedoan** [comment] 2022-01-26 18:28
I'll add some input validate when I rewrite my super ugly `configure.py` script :stuck_out_tongue:
